# Generated by Django 5.1.1 on 2024-11-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vendor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_images/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_images/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_images/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='location',
            field=models.CharField(default='Kochi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weddingvendor',
            name='date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='service_type',
            field=models.CharField(choices=[('Venue', 'Venue'), ('Catering', 'Catering'), ('Photography', 'Photography'), ('Decoration', 'Decoration'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('MakeUp', 'MakeUp')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='weddingvendor',
            unique_together={('vendor', 'date')},
        ),
    ]
