# Generated by Django 5.1.1 on 2024-11-09 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wedding_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bride_name', models.CharField(max_length=100)),
                ('groom_name', models.CharField(max_length=100)),
                ('wedding_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('additional_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
